source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'figaro'
gem 'slim'
gem 'slim-rails'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'high_voltage'
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'squeel'
gem 'email_validator'
gem 'cancan'
gem 'roadie', '~> 2.4.2'
gem 'draper', '~> 1.3.0'
group :development do
	gem 'better_errors'
	gem "binding_of_caller"
  gem 'quiet_assets'
  gem 'irbtools', :require => false
  gem 'pry'
end